--- @alias non-ascii.Encoding table<string, string[]>
--- @alias non-ascii.Decoding table<string, string[]>
--- @alias non-ascii.Schema non-ascii.Decoding
--- @alias non-ascii.Words table<string, boolean>
