local utils = require('non-ascii.utils')
-- Some special words that are not in the word files
local special_words = {
    -- English punctuation marks, this is usefull when you use 'cw' on a punctuation mark
    ['-'] = true,
    ['--'] = true,
    ['---'] = true,
    ['_'] = true,
    ['@'] = true,
    ['#'] = true,
    ['$'] = true,
    ['%'] = true,
    ['&'] = true,
    ['&&'] = true,
    ['*'] = true,
    ['+'] = true,
    ['++'] = true,
    ['/'] = true,
    ['//'] = true,
    ['\\'] = true,
    ['='] = true,
    ['=='] = true,
    ['!='] = true,
    ['~='] = true,
    [','] = true,
    ['.'] = true,
    ['...'] = true,
    ['|'] = true,
    ['||'] = true,
    ['!'] = true,
    ['?'] = true,
    [';'] = true,
    [':'] = true,
    ['"'] = true,
    ["'"] = true,
    ['('] = true,
    [')'] = true,
    ['()'] = true,
    ['[]'] = true,
    ['{}'] = true,
    ['<>'] = true,
    ['['] = true,
    [']'] = true,
    ['{'] = true,
    ['}'] = true,
    ['<'] = true,
    ['>'] = true,
    ['<='] = true,
    ['>='] = true,
    -- Chinese punctuation marks
    ['，'] = true,
    ['。'] = true,
    ['！'] = true,
    ['？'] = true,
    ['；'] = true,
    ['：'] = true,
    ['“'] = true,
    ['”'] = true,
    ['‘'] = true,
    ['’'] = true,
    ['（'] = true,
    ['）'] = true,
    ['【'] = true,
    ['】'] = true,
    ['《'] = true,
    ['》'] = true,
    ['「'] = true,
    ['」'] = true,
    ['〔'] = true,
    ['〕'] = true,
    ['…'] = true,
    ['—'] = true,
    ['·'] = true,
    ['￥'] = true,
    ['％'] = true,
    ['＃'] = true,
    ['＆'] = true,
    ['＊'] = true,
    ['＠'] = true,
    ['／'] = true,
    ['＼'] = true,
    ['＿'] = true,
    ['－'] = true,
    ['＋'] = true,
    ['＝'] = true,
    ['｜'] = true,
    ['｀'] = true,
    ['～'] = true,
}
local function is_word_separator(str, consider_newline)
    if str == '\n' then return consider_newline and not utils.is_operator() end
    return #str > 0 and not str:match('^[%w]') and not special_words[vim.fn.strcharpart(str, 0, 1)]
end

--- @type non-ascii.Config
return {
    word = {
        preffered_jump_length = { 9, 8, 7, 6, 5, 4, 3, 2, 1 },
        word_files = {},
        word_action_config = {
            w = { is_separator = function(str) return is_word_separator(str, true) end },
            b = { is_separator = function(str) return is_word_separator(str, true) end },
            e = { is_separator = function(str) return is_word_separator(str, true) end },
            ge = { is_separator = function(str) return is_word_separator(str, true) end },
            iw = { is_separator = function(str) return is_word_separator(str, false) end },
            aw = { is_separator = function(str) return is_word_separator(str, false) end },
        },
        words = special_words,
    },
}
